# Generated by Django 3.0 on 2020-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='calificacion',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='comentario',
            field=models.TextField(default=None),
        ),
    ]
