# Generated by Django 3.0 on 2020-09-11 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stalkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalkers',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Stalker', to=settings.AUTH_USER_MODEL),
        ),
    ]
