<<<<<<< HEAD
# Generated by Django 3.0 on 2020-09-13 04:57
=======
# Generated by Django 3.0 on 2020-09-14 20:25
>>>>>>> 2874ebdd32c1141643bcc8270953666798e31f1e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('Calificaciones', '0003_auto_20200913_0157'),
=======
        ('Calificaciones', '0002_calificaciones_trabajador'),
>>>>>>> 2874ebdd32c1141643bcc8270953666798e31f1e
        ('Stalkers', '0002_stalkers_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalkers',
            name='calificacion',
<<<<<<< HEAD
            field=models.ManyToManyField(related_name='st_califica', to='Calificaciones.Calificaciones'),
=======
            field=models.ManyToManyField(related_name='califica', to='Calificaciones.Calificaciones'),
>>>>>>> 2874ebdd32c1141643bcc8270953666798e31f1e
        ),
    ]
