# Generated by Django 3.0 on 2020-09-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificaciones', '0003_auto_20200913_0157'),
        ('Stalkers', '0002_stalkers_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalkers',
            name='calificacion',
            field=models.ManyToManyField(related_name='st_califica', to='Calificaciones.Calificaciones'),
        ),
    ]
