# Generated by Django 3.0 on 2020-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificaciones', '0002_calificaciones_trabajador'),
        ('Stalkers', '0002_stalkers_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalkers',
            name='calificacion',
            field=models.ManyToManyField(related_name='califica', to='Calificaciones.Calificaciones'),
        ),
    ]
